// Centralized response and error messages constant file

export const SYSTEM_MESSAGES = {
  MONGOURI_IS_NOT_DEFINED_IN_ENVIRONMENT_V: 'MONGO_URI is not defined in environment variables',
  FAILED_TO_STORE_TOKEN_IN_REDIS: 'Failed to store token in Redis',
} as const;

export const AUTH_MESSAGES = {
  REFRESH_TOKEN_MISSING: 'Refresh token missing',
  TOKEN_REFRESHED: 'Token refreshed',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  SOMETHING_WENT_WRONG_DURING_GOOGLE_AUTHE: 'Something went wrong during Google authentication',
  TOKEN_EXPIRED: 'Token expired.',
  UNAUTHORIZED_NO_USER_FOUND_IN_REQUEST: 'Unauthorized: No user found in request',
  ACCESS_DENIED_YOUR_ACCOUNT_HAS_BEEN_BLOC: 'Access denied: Your account has been blocked',
  INTERNAL_SERVER_ERROR_WHILE_CHECKING_BLO: 'Internal server error while checking blocked status',
  INVALID_GOOGLE_TOKEN: 'Invalid Google token',
  INVALID_ROLE: 'Invalid Role',
  LOGIN_SUCCESSFULL: 'login successfull',
  REGISTER_SUCCESSFULL: 'register successfull',
  GOOGLE_USER_VERIFIED: 'Google user verified',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  OLD_PASSWORD_IS_INCORRECT: 'Old password is incorrect',
  PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
  YOU_ARE_LOGIN_WITH_GOOGLEID: 'you are login with googleId',
  PASSWORD_RESET_LINK_SENT_TO_EMAIL: 'Password reset link sent to email',
  INVALID_TOKEN_MISSING_EXPIRATION_TIME: 'Invalid Token: Missing expiration time',
  LOGIN_SUCCESS: 'Login successful.',
  LOGIN_FAILED: 'Login failed. Please check your credentials.',
  USER_BLOCKED: 'Your account has been blocked. Please contact support.',
  USER_UNBLOCKED: 'User account has been unblocked successfully.',
  USER_SUSPENDED: 'User account has been suspended.',
  USER_BANNED: 'Your account has been permanently banned.',
  USER_DEACTIVATED: 'Your account has been deactivated. Please contact support to reactivate.',
  WORKER_BLOCKED: 'Worker account has been blocked.',
  WORKER_UNBLOCKED: 'Worker account has been unblocked successfully.',
  WORKER_SUSPENDED: 'Worker account suspended.',
  WORKER_REINSTATED: 'Worker account reinstated successfully.',
  REGISTRATION_SUCCESS: 'Registration successful.',
  REGISTRATION_FAILED: 'Registration failed. Please try again.',
  PASSWORD_CHANGED: 'Password changed successfully.',
  PASSWORD_RESET_SENT: 'Password reset email sent.',
  PASSWORD_RESET_SUCCESS: 'Password reset successful.',
  PASSWORD_RESET_FAILED: 'Failed to reset password.',
  EMAIL_VERIFICATION_SENT: 'Verification email sent successfully.',
  EMAIL_VERIFICATION_SUCCESS: 'Email successfully verified.',
  EMAIL_VERIFICATION_FAILED: 'Failed to verify email.',
  OTP_SENT: 'OTP sent successfully.',
  OTP_VERIFIED: 'OTP verified successfully.',
  OTP_INVALID: 'Invalid OTP. Please try again.',
  OTP_EXPIRED: 'OTP has expired. Please request a new one.',
} as const;

export const ADMIN_MESSAGES = {
  FAILED_TO_GET_USERS: 'Failed to get users',
  USER_UPDATION_FAILED: 'User updation failed',
  USER_UPDATEDISBLOCKED_ACTIVATED_BLOCKED_: 'User ${updated?.isBlocked ? \'activated\' : \'blocked\'} successfully',
  FAILED_TO_UPDATE_USER_STATUS: 'Failed to update user status',
  INVALID_STATUS: 'Invalid status',
  USER_UPDATEDSTATUS_INACTIVE_ACTIVE_SUCCE: 'User ${updated?.status ? \'inactive\' : \'active\'} successfully',
  DATA_ERROR: 'data error',
  SERVICE_ALREADY_EXISTS: 'Service already exists',
  SERVICE_CREATED_SUCCESSFULLY: 'Service created successfully',
  BOOKINGS_FETCHED_SUCCESSFULLY: 'Bookings fetched successfully',
  FAILED_TO_FETCH_BOOKINGS: 'Failed to fetch bookings',
  DATA_NOT_FOUNT: 'data not fount',
  SUCCESS_FULLY_FETCHED_DATA: 'success fully fetched Data',
  INTERNAL_ERROR: 'internal error',
  FETCH_SUCCESS_FULLY: 'fetch success fully',
  USER_IS_NOT_FOUNT: 'User is Not fount',
  USER_DATA_FETCH_SUCCESSFULLY: 'user data fetch successfully',
  BAD_REQUEST: 'Bad request',
  USER_DATA_IS_MISSING: 'User data is missing',
  USER_ID_IS_MISSING: 'User ID is missing',
  USER_NOT_FOUND: 'User not found',
  USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  NO_ADDRESSES_FOUND: 'No addresses found',
  ADDRESSES_RETRIEVED_SUCCESSFULLY: 'Addresses retrieved successfully',
  SOMTHING_IS_MISSING: 'somthing is missing',
  ADDRESS_ADDED_SUCCESSFULLY: 'Address added successfully',
  SOMETHING_IS_MISSING: 'Something is missing',
  SUCCESSFULLY_UPDATED: 'Successfully updated',
} as const;

export const CHAT_MESSAGES = {
  BOOKING_ID_IS_MISSING: 'Booking ID is missing',
  CHAT_NOT_FOUND: 'Chat not found',
  UNAUTHORIZED: 'Unauthorized',
  BOOKING_NOT_FOUNT: 'booking not fount',
  CHAT_ID_FETCH_SUCCESSFULLY: 'chat id fetch successfully',
  INTERNAL_ERROR: 'internal error',
  BOOKING_ID_NOT_FOUND: 'booking id not found',
  BOOKING_NOT_FOUND: 'booking not found',
  CHAT_FETCH_SUCCESSFULLY: 'chat fetch successfully',
  CHAT_ID_IS_REQUIRED: 'Chat ID is required',
  CHAT_HISTORY_FETCHED_SUCCESSFULLY: 'Chat history fetched successfully',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  CHAT_INBOX_FETCHED_SUCCESSFULLY: 'Chat inbox fetched successfully',
} as const;

export const NOTIFICATION_MESSAGES = {
  FAILED_TO_FETCH_NOTIFICATIONS: 'Failed to fetch notifications',
  FAILED_TO_UPDATE: 'Failed to update',
  UNAUTHORIZED: 'Unauthorized',
  ALL_NOTIFICATIONS_MARKED_AS_READ: 'All notifications marked as read',
  NOTIFICATION_SENT: 'Notification sent successfully.',
  REMINDER_SENT: 'Reminder sent successfully.',
  REMINDER_FAILED: 'Failed to send reminder.',
} as const;

export const REVIEW_MESSAGES = {
  BOOKINGID_AND_RATING_ARE_REQUIRED: 'BookingId and rating are required',
  RATING_MUST_BE_BETWEEN_1_AND_5: 'Rating must be between 1 and 5',
  SERVER_INTERFNAL_ERROR: 'server interfnal Error',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  BOOKING_NOT_FOUND: 'Booking not found',
  UNAUTHORIZED: 'Unauthorized',
  YOU_CAN_ONLY_REVIEW_COMPLETED_BOOKINGS: 'You can only review completed bookings',
  REVIEW_ALREADY_SUBMITTED: 'Review already submitted',
  USER_GIVE_RATING_STAR_FOR_YOUR_WORK: 'user give ${rating} star for your work',
  REVIEW_ADDED_SUCCESSFULLY: 'Review added successfully',
  FAILED_TO_ADD_REVIEW: 'Failed to add review',
  REVIEWS_FETCHED_SUCCESSFULLY: 'Reviews fetched successfully',
  REVIEW_SUBMITTED: 'Review submitted successfully.',
  REVIEW_UPDATED: 'Review updated successfully.',
  REVIEW_DELETED: 'Review deleted successfully.',
  RATING_SUBMITTED: 'Rating submitted successfully.',
} as const;

export const SERVICE_MESSAGES = {
  FAILED_TO_FETCH_WORKER_PROFILE: 'Failed to fetch worker profile',
  LATITUDE_LONGITUDE_AND_SERVICEID_ARE_REQ: 'Latitude, longitude and serviceId are required',
  WORKER_NOT_FOUND: 'Worker not found',
  DATA_FETCHED_SUCCESSFULLY: 'Data fetched Successfully',
  LATITUDE_AND_LONGITUDE_ARE_REQUIRED: 'Latitude and longitude are required',
  NO_SERVICES_FOUND_NEARBY: 'No services found nearby',
  NEARBY_SERVICES_FOUND: 'Nearby services found',
  WORKING_DETAILS_NOT_FOUND: 'Working details not found',
  AVAILABILITY_FETCHED_SUCCESSFULLY: 'Availability fetched successfully',
  FAILED_TO_FETCH_AVAILABILITY: 'Failed to fetch availability',
  WORKER_PROFILE_FETCHED_SUCCESSFULLY: 'Worker profile fetched successfully',
  SERVICE_CREATED: 'Service created successfully.',
  SERVICE_UPDATED: 'Service updated successfully.',
  SERVICE_DELETED: 'Service deleted successfully.',
  SERVICE_NOT_FOUND: 'Service not found.',
} as const;

export const GENERAL_MESSAGES = {
  VALIDATION_FAILED: 'Validation failed',
  UBOOKING_DETAILS_MISSING: 'ubooking details missing',
  BOOKINGID_ADDRESSID_AND_PAYMENTTYPE_ARE_: 'bookingId, addressId and paymentType are required',
  BOOKING_NOT_FOUND: 'Booking not found',
  ADVANCE_ALREADY_PAID: 'Advance already paid',
  FINAL_PAYMENT_ALREADY_COMPLETED: 'Final payment already completed',
  WALLET_PAYMENT_SUCCESSFUL: 'Wallet payment successful',
  TOKEN_MUST_BE_A_STRING: 'Token must be a string',
  INVALID_CREDENTIALS: 'Invalid credentials.',
  UNAUTHORIZED_ACCESS: 'Unauthorized access. Please log in.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  USER_ALREADY_EXISTS: 'User with this email already exists.',
  ACCOUNT_VERIFIED: 'Account successfully verified.',
  ACCOUNT_NOT_VERIFIED: 'Your account is not verified yet.',
  LOGOUT_SUCCESS: 'Logged out successfully.',
  PROFILE_UPDATED: 'Profile updated successfully.',
  PROFILE_UPDATE_FAILED: 'Failed to update profile.',
  SAME_CURR_NEW_PASSWORD: 'New password must be different from current password.',
  DATA_SENT_SUCCESS: 'Data sent successfully.',
  DATA_FETCH_SUCCESS: 'Data fetched successfully.',
  ALREADY_EXISTS: 'Data already exists.',
  CREATED: 'Created successfully.',
  UPDATE_SUCCESS: 'Updated successfully.',
  DELETE_SUCCESS: 'Deleted successfully.',
  SERVER_ERROR: 'An unexpected error occurred.',
  RESOURCE_NOT_FOUND: 'Requested resource not found.',
  TOKEN_BLACKLISTED: 'Session is no longer valid.',
  INVALID_TOKEN: 'Invalid session. Please log in again.',
  TOO_MANY_REQUESTS: 'Too many requests. Please try again later.',
  MAINTENANCE_MODE: 'The system is under maintenance. Please try again later.',
  LOADING: 'Please wait...',
  ACTION_SUCCESS: 'Action completed successfully.',
  ACTION_FAILED: 'Action failed. Please try again.',
} as const;

export const VALIDATION_MESSAGES = {
  PLEASE_SELECT_AN_ADDRESS_LABEL: 'Please select an address label',
  BUILDING_NAME_OR_FLAT_NUMBER_IS_REQUIRED: 'Building name or flat number is required',
  STREET_IS_REQUIRED: 'Street is required',
  AREA_IS_REQUIRED: 'Area is required',
  CITY_IS_REQUIRED: 'City is required',
  STATE_IS_REQUIRED: 'State is required',
  COUNTRY_IS_REQUIRED: 'Country is required',
  ENTER_A_VALID_10DIGIT_PHONE_NUMBER: 'Enter a valid 10-digit phone number',
  ENTER_A_VALID_6DIGIT_PIN_CODE: 'Enter a valid 6-digit PIN code',
  INVALID_LATITUDE_VALUE: 'Invalid latitude value',
  INVALID_LONGITUDE_VALUE: 'Invalid longitude value',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  NAME_MUST_BE_AT_LEAST_3_CHARACTERS_LONG: 'Name must be at least 3 characters long',
  NAME_MUST_BE_LESS_THAN_20_CHARACTERS: 'Name must be less than 20 characters',
  NAME_CAN_ONLY_CONTAIN_ALPHABETS_AND_SPAC: 'Name can only contain alphabets and spaces',
  PHONE_NUMBER_MUST_BE_EXACTLY_10_DIGITS: 'Phone number must be exactly 10 digits',
  INVALID_EXPERIENCE_RANGE: 'Invalid experience range',
  VALIDATION_ERROR: 'Validation failed. Please check your input.',
} as const;

export const WORKER_MESSAGES = {
  VALIDATION_FAILED: 'Validation failed',
  WORKER_NOT_FOUNT: 'worker not fount',
  DASHBOARDFETCH_SUCCESSFULLY: 'dashboardfetch successfully',
  WORKER_NOT_FOUND: 'Worker not found',
  WORKER_IS_NOT_FOUND: 'Worker is Not Found',
  FETCH_DATA_SUCCESSFULLY: 'fetch data successfully',
  FAILED_TO_UPDATE_WORKER_PROFILE: 'Failed to update worker profile',
  WORKER_PROFILE_UPDATED_SUCCESSFULLY: 'Worker profile updated successfully',
  DATA_NOT_FOUND: 'Data not found',
} as const;

export const PAYMENT_MESSAGES = {
  SUCCESSFULLY_PAYMENT_CREATED: 'Successfully Payment created',
  INTERNAL_ERROR: 'internal error',
  WALLET_NOT_FOUND: 'Wallet not found',
  TRANSACTIONS_FETCHED_SUCCESSFULLY: 'Transactions fetched successfully',
  WALLET_IS_FROZEN: 'Wallet is frozen',
  BALANCE_CREDITED_SUCCESSFULLY: 'Balance credited successfully',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  WALLET_DATA_FETCHED_SUCCESSFULLY: 'Wallet data fetched successfully',
  INSUFFICIENT_WALLET_BALANCE: 'Insufficient wallet balance',
  PAYMENT_COMPLETED_SUCCESSFULLY: 'Payment completed successfully',
  TRANSACTION_FAILED: 'Transaction failed.',
  PAYMENT_IN_PROGRESS: 'Payment already initiated for this booking. Please complete or cancel the previous payment.',
  PAYMENT_FAILED: 'Payment failed.',
  PAYMENT_SUCCESS: 'Payment successful.',
  REFUND_INITIATED: 'Refund initiated successfully.',
  REFUND_FAILED: 'Refund failed. Please contact support.',
  WALLET_BALANCE_LOW: 'Insufficient wallet balance.',
} as const;

export const BOOKING_MESSAGES = {
  USER_NOT_FOUND: 'User not Found',
  MISSING_REQUIRED_FIELDS_TIME_DATE_OR_DES: 'Missing required fields (time, date, or description)',
  INVALID_DATE_FORMAT: 'Invalid date format',
  WORKER_IS_NOT_FOUND: 'worker is not found',
  SLOT_ALREADY_BOOKED_BY_ANOTHER_USER: 'Slot already booked by another user',
  FAILED_TO_CREATE_BOOKING: 'Failed to create booking',
  SLOT_LOCKED_FOR_10_MINUTES: 'Slot locked for 10 minutes',
  INTERNAL_ERROR: 'internal error',
  BOOKING_DETAILS_NOT_FOUND: 'booking details not found',
  BOOKING_DETAILS_FOUND: 'booking details  found',
  MISSING_BOOKINGID_OR_WORKERID: 'Missing bookingId or workerId',
  ENDING_TIME_AND_REQUIRED_ITEMS_ARE_MANDA: 'Ending time and required items are mandatory',
  BOOKING_NOT_FOUND_OR_UNAUTHORIZED: 'Booking not found or unauthorized',
  WORKER_DETAILS_UPDATED_SUCCESSFULLY: 'Worker details updated successfully',
  INTERNAL_SERVER_ERROR_WHILE_UPDATING_DET: 'Internal server error while updating details',
  MISSING_BOOKINGID_OR_PAYMENTTYPE: 'Missing bookingId or paymentType',
  BOOKING_NOT_FOUND: 'Booking not found',
  ADVANCE_PAYMENT_NOT_COMPLETED: 'Advance payment not completed',
  ADVANCE_PAYMENT_VERIFIED: 'Advance payment verified',
  FINAL_PAYMENT_NOT_COMPLETED: 'Final payment not completed',
  FINAL_PAYMENT_VERIFIED: 'Final payment verified',
  INVALID_PAYMENT_TYPE: 'Invalid payment type',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  WORKER_ALREADY_REJECTED_THIS_BOOKING: 'worker already rejected this booking',
  ONLY_STATUS_WITH_PENDING_AND_CONIFIRMED_: 'Only status with pending and conifirmed can cancel',
  USER_CANCEL_THE_BOOKING: 'user cancel the booking',
  NO_BOOKINGS_FOUND: 'No bookings found',
  ONGOING_BOOKINGS_FETCHED_SUCCESSFULLY: 'Ongoing bookings fetched successfully',
  BOOKIING_DETAIL_IS_MISSING: 'bookiing detail is missing',
  BOOKING_NOT_FOUNT: 'booking not fount',
  SUCCESSFULLY_FETCHED_DATA: 'successfully fetched data',
  END_TIME_MUST_BE_GREATER_THAN_START_TIME: 'End time must be greater than start time',
  TIME_CONFLICT_WITH_ANOTHER_APPROVED_BOOK: 'Time conflict with another approved booking',
  INVALID_ADDITIONAL_ITEM: 'Invalid additional item',
  WORKER_APPROVED_YOUR_BOOKING: 'worker  Approved your booking',
  SERVICE_APPROVED_SUCCESSFULLY: 'Service approved successfully',
  ALREADY_REJECTED: 'Already rejected',
  USER_WALLET_ERROR: 'user wallet error',
  USER_BOOKING_UPDATION_FAILED: 'user booking updation failed',
  WORKER_REJECTED_YOUR_BOOKING: 'worker  rejected your booking',
  SERVICE_REJECTED_SUCCESSFULLY: 'Service rejected successfully',
  SOMETHING_WENT_WRONG: 'something went wrong',
  REQUESTS_FETCHED_SUCCESSFULLY: 'Requests fetched successfully',
  WORKER_DATA_NOT_FONT: 'worker data not font',
  DATA_NOT_FOUNT: 'data not fount',
  DATA_FETCH_SUCCESSFULLY: 'data fetch successfully',
  BOOKING_DATA_MISSING: 'booking data missing',
  BOOKING_DATA_NOT_FOUNT: 'booking data not fount',
  INTERNAL_EROR: 'Internal Eror',
  BOOKING_DEATAILS_IS_NOT_FOUNT: 'booking deatails is not fount ',
  BOOKING_DETAILS_IS_NOT_FOUNT: 'booking details is not fount ',
  WORKER_REACHED_TO_YOUR_LOCATION: 'worker reached to your location',
  SUCCESSFULLY_GENERATED_OTP: 'successfully generated otp',
  BOOKING_DETAIL_MISSING: 'booking detail missing',
  VALIDATION_NOT_FOUNT: 'validation  not fount ',
  WORKER_VARIFICATION_FAILED: 'worker varification failed',
  WORKER_SUCCESSFULLY_VERIFIED: 'worker successfully verified',
  BOOKING_ID_IS_NOT_FOUNT: 'booking Id is not fount',
  BOOKING_UPDATETION_FAILED: 'booking updatetion failed',
  BOOKING_IS_NOT_FOUNT: 'booking is not fount',
  WORK_IS_COMPLATE: ' work is complate',
  SUCCESSFULLY_UPDATED: 'successfully updated',
  SUCCESSFULLY_FETCH_DATA: 'successfully fetch data',
  BOOKING_SUCCESS: 'Service booked successfully.',
  BOOKING_FAILED: 'Failed to book service. Please try again.',
  BOOKING_CANCELLED: 'Booking cancelled successfully.',
  BOOKING_ALREADY_EXISTS: 'You already have a booking for this time slot.',
  SLOT_UNAVAILABLE: 'Selected slot is no longer available.',
} as const;

export const MESSAGES = {
  ...SYSTEM_MESSAGES,
  ...AUTH_MESSAGES,
  ...ADMIN_MESSAGES,
  ...CHAT_MESSAGES,
  ...NOTIFICATION_MESSAGES,
  ...REVIEW_MESSAGES,
  ...SERVICE_MESSAGES,
  ...GENERAL_MESSAGES,
  ...VALIDATION_MESSAGES,
  ...WORKER_MESSAGES,
  ...PAYMENT_MESSAGES,
  ...BOOKING_MESSAGES,
} as const;

export type MESSAGES_TYPE = typeof MESSAGES;
